### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by lewisking** [bih/spotify-token-swap-service#3]
Hey,

I'm having issues with refresh tokens. I'm sending the following to a heroku instance:

```
let refreshToken = `https://poolsidelive.herokuapp.com/api/refresh_token?refresh_token=Hqomr5nlHgJNTTi7CIaOWUU6kHfm6bGO1Td+vWJqmkdYrMVg5IxyAJBdckHJ%0AIcFNOUAzPnxxwRf/PiP8P5HpPyrnWK0WhuE5SjnXjEieadwOajtyXygsfHH2%0AcLe0AkWEsQh9HUqxVruR4bmw/hcXa4CA1RxnhyFStUwLszw594VfBfcrPy8x%0AGA==%0A`

API.post(refreshToken).then((response) => {
  console.log("Updating access tokens", response);
});
```

Which returns the following:

"error: "invalid refresh_token".

Everything else I do works correctly (getting access tokens, authoring with Spotify. The only thing I can see with the error is “OpenSSL::Cipher::CipherError” is triggering the error I'm seeing. I'm not sure why I am getting that!

Any help would be greatly appreciated.

**Comment by bih** [comment]
The issue is that you need to URL encode your `refresh_token`. That'll fix your problem. Also I've added a patch that'll remove the `OpenSSL::Cipher::CipherError` issue (which is related to a dependency). You'll need to update your code with the latest changes to `master` in this GitHub repository.

Hope this helps! :)

**Comment by lewisking** [comment]
Hey @bih I'm afraid I'm still having an issue with this.

I'm sending the following (after updating the heroku app) and still getting "invalid refresh_token" issue.

https://poolside.herokuapp.com/api/refresh_token?refresh_token=pIH72vaEsZLvnxmrtb9cKXkseodqij0ZcscVEpedtF64/yRK6WPoYFGM+5Iz%0A/d/16aGRW6AwoLc2qq8YO5uLqyY+kq8zYr0DwpeuGQ2vAaQ/JsnZ0fY6bPyt%0AexIHbcFFTS8BFm+tnXPKCgZbLUc9nz0zW1T25AYXK6kJeXO2WoEmxh7UjxDs%0AUw==%0A
