### ISSUE TITLE
I can't seem to get refresh tokens (hosted on Heroku)

### ISSUE THREAD

**Issue by NeuronButter** [bih/spotify-token-swap-service#4]
Hi! I've tried passing in a refresh token, looking like this: `DbLMSKlJyqaSSdWSyEQMenkxcPKDcjY5swShRVWA93R9oE8pVnGm3qiid6E7 +ksYYRyKXaG5JF5Ip+iTmIY5LQOjbf2D9nNEdv7+KLIvTiZe7SYXX3V0Uqpv ga3CtJP79i0OXU9YZoQcY+y9cmS21SiKzRWBfntiYamSL6fU4KzTa5aUMBNv pA==` through both my app with the Fetch API in JavaScript and in Postman. The error keeps coming up with `"error": "invalid refresh_token"`

**Comment by NeuronButter** [comment]
Never mind, all good! Looks like JavaScript handles \n different to other platforms. All fixed up now!

**Comment by alfredoxyanez** [comment]
@NeuronButter How exactly did you fix this? Ive tried to pass the refresh_token with and without \n and it doesn't seem to work

**Comment by NeuronButter** [comment]
I'm heading out now, but I'll upload my source code to fix it!

**Comment by alfredoxyanez** [comment]
Thanks!

**Comment by alfredoxyanez** [comment]
For anyone facing this issue you have to URL encode your refresh_token. You can try this website to debug https://www.urlencoder.org
